(() => {
const key='grossmann-event-products';
let selected=[];try{selected=JSON.parse(sessionStorage.getItem(key)||'[]');if(!Array.isArray(selected))selected=[];}catch{}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const card=p=>`<article class="product-card"><div class="product-photo">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name+' · '+p.package)}" width="440" height="440" loading="lazy">`:'<span class="missing-image">Produktabbildung folgt</span>'}</div><div class="product-info"><span class="product-brand">${esc(p.brand)}</span><h3>${esc(p.name)}</h3><p class="product-package">${esc(p.package)}</p><button class="product-select" data-product="${esc(p.id)}" aria-pressed="${selected.some(s=>s.id===p.id)}">${selected.some(s=>s.id===p.id)?'✓ Ausgewählt':'Für mein Event auswählen'}</button></div></article>`;
fetch('/catalog-data.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(products=>{
 products.sort((a,b)=>a.manufacturer.localeCompare(b.manufacturer,'de')||a.brand.localeCompare(b.brand,'de')||a.name.localeCompare(b.name,'de'));
 const preview=document.querySelector('#product-preview');
 if(preview){const names=['Elisabethen Still','Coca Cola Original','Rapps Apfelsaft','Tegernseer hell'];preview.innerHTML=names.map(n=>products.find(p=>p.name===n)).filter(Boolean).map(card).join('');}
 const grid=document.querySelector('#products');let shown=24;const filters=['manufacturer','brand','category'].map(id=>document.getElementById(id));const search=document.querySelector('#product-search');
 const count=()=>{const node=document.querySelector('#selection-count');if(node)node.textContent=selected.length?`${selected.length} Produkte für Ihr Event ausgewählt`:'Keine Produkte ausgewählt';};
 const options=(node,items,label)=>{const value=node.value;node.innerHTML=`<option value="">${label}</option>`+[...new Set(items)].sort((a,b)=>a.localeCompare(b,'de')).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if([...node.options].some(o=>o.value===value))node.value=value;};
 function render(){const q=search.value.trim().toLocaleLowerCase('de');const results=products.filter(p=>filters.every(f=>!f.value||p[f.id]===f.value)&&[p.name,p.brand,p.manufacturer,p.package].join(' ').toLocaleLowerCase('de').includes(q));grid.innerHTML=results.length?results.slice(0,shown).map(card).join(''):'<p class="catalog-empty">Keine passenden Produkte gefunden. Ändern Sie die Suche oder setzen Sie die Filter zurück.</p>';document.querySelector('#catalog-count').textContent=`${results.length} passende Produkte · ${Math.min(shown,results.length)} angezeigt`;document.querySelector('#load-more').hidden=shown>=results.length;count();}
 if(grid){options(filters[0],products.map(p=>p.manufacturer),'Alle Hersteller');options(filters[1],products.map(p=>p.brand),'Alle Marken');options(filters[2],products.map(p=>p.category),'Alle Produktgruppen');filters.forEach(f=>f.addEventListener('change',()=>{shown=24;if(f.id==='manufacturer')options(filters[1],products.filter(p=>!f.value||p.manufacturer===f.value).map(p=>p.brand),'Alle Marken');render();}));search.addEventListener('input',()=>{shown=24;render();});document.querySelector('#load-more').addEventListener('click',()=>{shown+=24;render();});document.querySelector('#reset-filters').addEventListener('click',()=>{filters.forEach(f=>f.value='');options(filters[1],products.map(p=>p.brand),'Alle Marken');search.value='';shown=24;render();});render();}
 document.addEventListener('click',e=>{const button=e.target.closest('[data-product]');if(!button)return;const p=products.find(p=>p.id===button.dataset.product);if(!p)return;selected=selected.some(s=>s.id===p.id)?selected.filter(s=>s.id!==p.id):[...selected,{id:p.id,name:p.name,package:p.package}];try{sessionStorage.setItem(key,JSON.stringify(selected));}catch{}button.setAttribute('aria-pressed',String(selected.some(s=>s.id===p.id)));button.textContent=selected.some(s=>s.id===p.id)?'✓ Ausgewählt':'Für mein Event auswählen';count();});
}).catch(()=>{const node=document.querySelector('#catalog-count')||document.querySelector('#product-preview');if(node)node.textContent='Das Sortiment konnte nicht geladen werden. Bitte laden Sie die Seite erneut.';});
})();
